// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace MathHub.Web.Controllers
{
    public partial class DiscussionController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected DiscussionController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Detail()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Detail);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Reply()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Reply);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Comment()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Comment);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public DiscussionController Actions { get { return MVC.Discussion; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Discussion";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Discussion";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string Trending = "Trending";
            public readonly string Mytags = "Mytags";
            public readonly string Unanswered = "Unanswered";
            public readonly string Newest = "Newest";
            public readonly string Create = "Create";
            public readonly string Detail = "Detail";
            public readonly string Reply = "Reply";
            public readonly string Comment = "Comment";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string Trending = "Trending";
            public const string Mytags = "Mytags";
            public const string Unanswered = "Unanswered";
            public const string Newest = "Newest";
            public const string Create = "Create";
            public const string Detail = "Detail";
            public const string Reply = "Reply";
            public const string Comment = "Comment";
        }


        static readonly ActionParamsClass_Create s_params_Create = new ActionParamsClass_Create();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Create CreateParams { get { return s_params_Create; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Create
        {
            public readonly string discussionVM = "discussionVM";
        }
        static readonly ActionParamsClass_Detail s_params_Detail = new ActionParamsClass_Detail();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Detail DetailParams { get { return s_params_Detail; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Detail
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_Reply s_params_Reply = new ActionParamsClass_Reply();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Reply ReplyParams { get { return s_params_Reply; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Reply
        {
            public readonly string id = "id";
            public readonly string offset = "offset";
        }
        static readonly ActionParamsClass_Comment s_params_Comment = new ActionParamsClass_Comment();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Comment CommentParams { get { return s_params_Comment; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Comment
        {
            public readonly string postId = "postId";
            public readonly string offset = "offset";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
            }
            static readonly _LayoutsClass s_Layouts = new _LayoutsClass();
            public _LayoutsClass Layouts { get { return s_Layouts; } }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public partial class _LayoutsClass
            {
                static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
                public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
                public class _ViewNamesClass
                {
                    public readonly string _DiscussionCreateLayout = "_DiscussionCreateLayout";
                    public readonly string _DiscussionDetailLayout = "_DiscussionDetailLayout";
                    public readonly string _DiscussionListLayout = "_DiscussionListLayout";
                }
                public readonly string _DiscussionCreateLayout = "~/Views/Discussion/Layouts/_DiscussionCreateLayout.cshtml";
                public readonly string _DiscussionDetailLayout = "~/Views/Discussion/Layouts/_DiscussionDetailLayout.cshtml";
                public readonly string _DiscussionListLayout = "~/Views/Discussion/Layouts/_DiscussionListLayout.cshtml";
            }
            static readonly _PartialsClass s_Partials = new _PartialsClass();
            public _PartialsClass Partials { get { return s_Partials; } }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public partial class _PartialsClass
            {
                static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
                public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
                public class _ViewNamesClass
                {
                    public readonly string _AnswerItem = "_AnswerItem";
                    public readonly string _AnswerList = "_AnswerList";
                    public readonly string _AnswerPostForm = "_AnswerPostForm";
                    public readonly string _CommentItem = "_CommentItem";
                    public readonly string _CommentList = "_CommentList";
                    public readonly string _CommentPostForm = "_CommentPostForm";
                    public readonly string _DiscussionItem = "_DiscussionItem";
                    public readonly string _HintItem = "_HintItem";
                    public readonly string _HintList = "_HintList";
                    public readonly string _HintPostForm = "_HintPostForm";
                }
                public readonly string _AnswerItem = "~/Views/Discussion/Partials/_AnswerItem.cshtml";
                public readonly string _AnswerList = "~/Views/Discussion/Partials/_AnswerList.cshtml";
                public readonly string _AnswerPostForm = "~/Views/Discussion/Partials/_AnswerPostForm.cshtml";
                public readonly string _CommentItem = "~/Views/Discussion/Partials/_CommentItem.cshtml";
                public readonly string _CommentList = "~/Views/Discussion/Partials/_CommentList.cshtml";
                public readonly string _CommentPostForm = "~/Views/Discussion/Partials/_CommentPostForm.cshtml";
                public readonly string _DiscussionItem = "~/Views/Discussion/Partials/_DiscussionItem.cshtml";
                public readonly string _HintItem = "~/Views/Discussion/Partials/_HintItem.cshtml";
                public readonly string _HintList = "~/Views/Discussion/Partials/_HintList.cshtml";
                public readonly string _HintPostForm = "~/Views/Discussion/Partials/_HintPostForm.cshtml";
            }
            static readonly _ViewsClass s_Views = new _ViewsClass();
            public _ViewsClass Views { get { return s_Views; } }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public partial class _ViewsClass
            {
                static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
                public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
                public class _ViewNamesClass
                {
                    public readonly string CreateDiscussion = "CreateDiscussion";
                    public readonly string DetailDiscussion = "DetailDiscussion";
                    public readonly string ListAllDiscussion = "ListAllDiscussion";
                }
                public readonly string CreateDiscussion = "~/Views/Discussion/Views/CreateDiscussion.cshtml";
                public readonly string DetailDiscussion = "~/Views/Discussion/Views/DetailDiscussion.cshtml";
                public readonly string ListAllDiscussion = "~/Views/Discussion/Views/ListAllDiscussion.cshtml";
            }
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_DiscussionController : MathHub.Web.Controllers.DiscussionController
    {
        public T4MVC_DiscussionController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void TrendingOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Trending()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Trending);
            TrendingOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void MytagsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Mytags()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Mytags);
            MytagsOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void UnansweredOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Unanswered()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Unanswered);
            UnansweredOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void NewestOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Newest()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Newest);
            NewestOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void CreateOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Create()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Create);
            CreateOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void CreateOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, MathHub.Web.Models.DiscussionVM.CreateDiscussionVM discussionVM);

        [NonAction]
        public override System.Web.Mvc.ActionResult Create(MathHub.Web.Models.DiscussionVM.CreateDiscussionVM discussionVM)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Create);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "discussionVM", discussionVM);
            CreateOverride(callInfo, discussionVM);
            return callInfo;
        }

        [NonAction]
        partial void DetailOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult Detail(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Detail);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            DetailOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void ReplyOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id, int offset);

        [NonAction]
        public override System.Web.Mvc.ActionResult Reply(int id, int offset)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Reply);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "offset", offset);
            ReplyOverride(callInfo, id, offset);
            return callInfo;
        }

        [NonAction]
        partial void CommentOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int postId, int offset);

        [NonAction]
        public override System.Web.Mvc.ActionResult Comment(int postId, int offset)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Comment);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "postId", postId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "offset", offset);
            CommentOverride(callInfo, postId, offset);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
