//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MathHub.Entity.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public int Id { get; set; }
        public System.DateTime LastSeenInvition { get; set; }
        public System.DateTime LastSeenSubcription { get; set; }
        public System.DateTime LastSeenReceivedMedal { get; set; }
        public System.DateTime LastPermissionGain { get; set; }
        public System.DateTime LastSeenPermissionGain { get; set; }
        public string NewPasswordKey { get; set; }
        public System.DateTime NewPasswordRequestedDate { get; set; }
        public string NewEmail { get; set; }
        public string NewEmailKey { get; set; }
        public string LastLogin { get; set; }
        public string LastIp { get; set; }
    
        public virtual User User { get; set; }
    }
}
