//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MathHub.Entity.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment : Post
    {
        public Nullable<int> ReplyId { get; set; }
        public Nullable<int> MainPostId { get; set; }
    
        public virtual Reply Reply { get; set; }
        public virtual MainPost MainPost { get; set; }
    }
}
