//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MathHub.Entity.Entity
{
    using System;
    using System.Collections.Generic;
    
    public abstract partial class MainPost : Post
    {
        public MainPost()
        {
            this.PostTags = new HashSet<PostTag>();
            this.FavoritePosts = new HashSet<FavoritePost>();
            this.Comments = new HashSet<Comment>();
            this.ViewHits = new HashSet<ViewHit>();
            this.Replies = new HashSet<Reply>();
            this.Shares = new HashSet<Share>();
        }
    
        public string Title { get; set; }
    
        public virtual ICollection<PostTag> PostTags { get; set; }
        public virtual ICollection<FavoritePost> FavoritePosts { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<ViewHit> ViewHits { get; set; }
        public virtual ICollection<Reply> Replies { get; set; }
        public virtual ICollection<Share> Shares { get; set; }
    }
}
