//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MathHub.Entity.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MathHubModelContainer : DbContext
    {
        public MathHubModelContainer()
            : base("name=MathHubModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<User> Users { get; set; }
        public DbSet<Tag> Tags { get; set; }
        public DbSet<FavoriteTag> FavoriteTags { get; set; }
        public DbSet<PostTag> PostTags { get; set; }
        public DbSet<Post> Posts { get; set; }
        public DbSet<Category> Categories { get; set; }
        public DbSet<BlogProblem> BlogProblems { get; set; }
        public DbSet<DiscusstionProblem> DiscusstionProblems { get; set; }
        public DbSet<FavoritePost> FavoritePosts { get; set; }
        public DbSet<Invitation> Invitations { get; set; }
        public DbSet<ViewHit> ViewHits { get; set; }
        public DbSet<Report> Reports { get; set; }
        public DbSet<ReportReason> ReportReasons { get; set; }
        public DbSet<Vote> Votes { get; set; }
        public DbSet<ScoreRule> ScoreRules { get; set; }
        public DbSet<Subscription> Subscriptions { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<Assessment> Assessments { get; set; }
        public DbSet<Function> Functions { get; set; }
        public DbSet<Permission> Permissions { get; set; }
        public DbSet<ScorePermission> ScorePermissions { get; set; }
        public DbSet<Medal> Medals { get; set; }
        public DbSet<Reward> Rewards { get; set; }
        public DbSet<Image> Images { get; set; }
        public DbSet<Profile> Profiles { get; set; }
        public DbSet<Conversation> Conversations { get; set; }
        public DbSet<Attendance> Attendances { get; set; }
        public DbSet<Message> Messages { get; set; }
        public DbSet<Topic> Topics { get; set; }
        public DbSet<TopicEnrollment> TopicEnrollments { get; set; }
        public DbSet<BlogInTopic> BlogInTopics { get; set; }
        public DbSet<Share> Shares { get; set; }
        public DbSet<StringResource> StringResources { get; set; }
        public DbSet<FollowPost> FollowPosts { get; set; }
        public DbSet<Activity> Activities { get; set; }
        public DbSet<LoginSession> LoginSessions { get; set; }
    }
}
