//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MathHub.Entity.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public Post()
        {
            this.Reports = new HashSet<Report>();
            this.Votes = new HashSet<Vote>();
            this.Follows = new HashSet<FollowPost>();
        }
    
        public int Id { get; set; }
        public string Content { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
        public int UserId { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<Report> Reports { get; set; }
        public virtual ICollection<Vote> Votes { get; set; }
        public virtual ICollection<FollowPost> Follows { get; set; }
    }
}
