//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MathHub.Entity.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile
    {
        public int Id { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string School { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Website { get; set; }
        public string Location { get; set; }
        public string Facebook { get; set; }
        public string Summary { get; set; }
        public Nullable<int> View { get; set; }
    
        public virtual User User { get; set; }
    }
}
