//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MathHub.Entity.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reply : Post
    {
        public Reply()
        {
            this.Comments = new HashSet<Comment>();
        }
    
        public ReplyEnum Type { get; set; }
        public Nullable<int> MainPostId { get; set; }
        public Nullable<int> TopicId { get; set; }
    
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual MainPost MainPost { get; set; }
        public virtual Topic Topic { get; set; }
    }
}
