//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MathHub.Entity.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int Id { get; set; }
        public int PostId { get; set; }
        public int ReportReasonId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string OtherReason { get; set; }
    
        public virtual Post Post { get; set; }
        public virtual ReportReason ReportReason { get; set; }
    }
}
