//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MathHub.Entity.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reward
    {
        public int Id { get; set; }
        public System.DateTime DateCreated { get; set; }
        public int UserId { get; set; }
        public int MedalId { get; set; }
    
        public virtual User User { get; set; }
        public virtual Medal Medal { get; set; }
    }
}
