//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MathHub.Entity.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscription
    {
        public int Id { get; set; }
        public System.DateTime DateCreated { get; set; }
        public int FollowingId { get; set; }
        public int FollowerId { get; set; }
        public System.DateTime DateSeen { get; set; }
        public bool SubsProblem { get; set; }
        public bool SubsBlog { get; set; }
        public bool SubsDiscussion { get; set; }
        public bool SubsShare { get; set; }
    
        public virtual User Following { get; set; }
        public virtual User Follower { get; set; }
    }
}
