//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MathHub.Entity.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Topic
    {
        public Topic()
        {
            this.TopicEnrollments = new HashSet<TopicEnrollment>();
            this.BlogInTopics = new HashSet<BlogInTopic>();
            this.Replies = new HashSet<Reply>();
        }
    
        public int Id { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public int CreatorId { get; set; }
    
        public virtual User Creator { get; set; }
        public virtual ICollection<TopicEnrollment> TopicEnrollments { get; set; }
        public virtual ICollection<BlogInTopic> BlogInTopics { get; set; }
        public virtual ICollection<Reply> Replies { get; set; }
    }
}
