//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MathHub.Entity.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Tags = new HashSet<Tag>();
            this.FavoriteTags = new HashSet<FavoriteTag>();
            this.Posts = new HashSet<Post>();
            this.Categories = new HashSet<Category>();
            this.FavoritePosts = new HashSet<FavoritePost>();
            this.Invitations = new HashSet<Invitation>();
            this.Votes = new HashSet<Vote>();
            this.Followers = new HashSet<Subscription>();
            this.Followings = new HashSet<Subscription>();
            this.Assessments = new HashSet<Assessment>();
            this.Rewards = new HashSet<Reward>();
            this.Attendances = new HashSet<Attendance>();
            this.Topics = new HashSet<Topic>();
            this.TopicEnrollments = new HashSet<TopicEnrollment>();
            this.Shares = new HashSet<Share>();
            this.Follows = new HashSet<FollowPost>();
        }
    
        public int Id { get; set; }
        public string Username { get; set; }
        public Nullable<int> Score { get; set; }
    
        public virtual ICollection<Tag> Tags { get; set; }
        public virtual ICollection<FavoriteTag> FavoriteTags { get; set; }
        public virtual ICollection<Post> Posts { get; set; }
        public virtual ICollection<Category> Categories { get; set; }
        public virtual ICollection<FavoritePost> FavoritePosts { get; set; }
        public virtual ICollection<Invitation> Invitations { get; set; }
        public virtual ICollection<Vote> Votes { get; set; }
        public virtual ICollection<Subscription> Followers { get; set; }
        public virtual ICollection<Subscription> Followings { get; set; }
        public virtual ICollection<Assessment> Assessments { get; set; }
        public virtual ICollection<Reward> Rewards { get; set; }
        public virtual ICollection<Attendance> Attendances { get; set; }
        public virtual ICollection<Topic> Topics { get; set; }
        public virtual ICollection<TopicEnrollment> TopicEnrollments { get; set; }
        public virtual ICollection<Share> Shares { get; set; }
        public virtual ICollection<FollowPost> Follows { get; set; }
        public virtual LoginSession LoginSession { get; set; }
        public virtual Activity Activity { get; set; }
        public virtual Profile Profile { get; set; }
        public virtual Image Avatar { get; set; }
    }
}
